version: "3.2"
services:
  wrapper_api:
    container_name: wrapper_api
    build: .
    ports:
      - "5000:5000"

  redis:
    container_name: redis
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

volumes:
  redis-data:
