version: "3.2"
services:
  wrapper_api:
    container_name: wrapper_api
    build: .
    ports:
      - 5000:5000
    environment:
      - OPENWEATHER_ENDPOINT=https://api.openweathermap.org/data/2.5/weather
      - OPENWEATHER_APIKEY=5ba6e1ac0975af545801d9227ad1e376
      - CACHE_TTL_SECONDS=300
      - DEFAULT_MAX_NUMBER=5
      - REDIS_ENDPOINT=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/redis-data

volumes:
  redis-data:
